/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package main

import javax.swing.*
import java.awt.*
import java.awt.event.*
/***

**/
class App {

    static void main(String[] args) {
        Rule[] rules = [new ConwaySimplified()];
        def board = new Board(160, rules);
        board.initialize()
        
        def renderer = new Renderer(board, 5);
        renderer.setUpGui()
    }
}

